# Generated by Django 5.1.4 on 2025-01-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='نمایش در سایت'),
        ),
    ]
