# Generated by Django 5.1.4 on 2025-01-31 11:36

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_faq_is_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='نام')),
                ('commented_at', django_jalali.db.models.jDateField(verbose_name='تاریخ ثبت نظر')),
                ('text', models.TextField(max_length=450, verbose_name='نظر')),
                ('is_visible', models.BooleanField(default=True, verbose_name='نمایش در سایت')),
            ],
            options={
                'verbose_name': 'نظر کاربران',
                'verbose_name_plural': 'نظرات کاربران',
            },
        ),
    ]
