# Generated by Django 5.1.4 on 2025-01-31 11:48

import django_jalali.db.models
import jdatetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='first_name',
        ),
        migrations.AlterField(
            model_name='comment',
            name='commented_at',
            field=django_jalali.db.models.jDateField(default=jdatetime.date.today, verbose_name='تاریخ ثبت نظر'),
        ),
    ]
