# Generated by Django 5.1.4 on 2025-01-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_comment_first_name_alter_comment_commented_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='hi', max_length=30, verbose_name='نام'),
            preserve_default=False,
        ),
    ]
