# Generated by Django 5.1.4 on 2025-02-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='is_video',
            field=models.BooleanField(default=False, verbose_name='ویدیو'),
        ),
    ]
