# Generated by Django 5.1.4 on 2025-01-07 12:05

import cart.models
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to=cart.models.document_path, verbose_name='فایل')),
                ('thumbnail', django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=80, scale=None, size=[60, 70], upload_to=cart.models.document_path)),
            ],
        ),
    ]
