# Generated by Django 5.1.4 on 2025-01-07 12:08

import cart.models
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, editable=False, force_format='PNG', keep_meta=True, null=True, quality=100, scale=None, size=[60, 70], upload_to=cart.models.document_path),
        ),
    ]
