# Generated by Django 5.1.4 on 2025-01-09 16:31

import cart.models
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_documents_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, editable=False, force_format='JPEG', keep_meta=True, null=True, quality=100, scale=None, size=[60, 70], upload_to=cart.models.document_path),
        ),
    ]
