# Generated by Django 5.1.4 on 2025-01-18 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_documents_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documents',
            options={'verbose_name': 'فایل', 'verbose_name_plural': 'فایل ها'},
        ),
        migrations.RemoveField(
            model_name='documents',
            name='thumbnail',
        ),
    ]
