# Generated by Django 5.1.4 on 2025-02-03 12:30

import cart.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_documents_options_remove_documents_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='pdf',
            field=models.FileField(upload_to=cart.models.document_path, validators=[cart.models.pdf_size_validator], verbose_name='فایل'),
        ),
    ]
