# Generated by Django 5.1.4 on 2025-01-09 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='نام')),
                ('last_name', models.CharField(max_length=255, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(max_length=255, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('province', models.CharField(blank=True, max_length=255, null=True, verbose_name='استان')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='شهرستان')),
                ('address', models.CharField(max_length=300, verbose_name='آدرس')),
                ('postal_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='کد پستی')),
                ('notes', models.TextField(blank=True, max_length=500, null=True, verbose_name='یادداشت های سفارش')),
                ('order_id', models.CharField(default='', max_length=10, verbose_name='کد سفارش')),
                ('postal_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='کد رهگیری پست')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('status', models.CharField(choices=[('ثبت شده', 'ثبت شده'), ('پرداخت شده', 'پیداخت شده'), ('آماده سازی سفارش', 'آماده سازی سفارش'), ('در حال ارسال', 'در حال ارسال'), ('تکمیل شد', 'تکمیل شد'), ('لغو شد', 'لغو شد')], default='ثبت شده', max_length=21, verbose_name='وضعیت')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش ها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='سری')),
                ('size', models.CharField(choices=[('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5')], max_length=2, verbose_name='اندازه')),
                ('color', models.CharField(choices=[('W&B', 'سیاه سفید'), ('C50', 'رنگی 50 درصد'), ('C100', 'رنگی 100 درصد')], max_length=21, verbose_name='رنگ')),
                ('print_type', models.CharField(choices=[('ONE_SIDE', 'یک رو'), ('BOTH_SIDES', 'دو رو')], max_length=21, verbose_name='نوع چاپ')),
                ('extra', models.CharField(choices=[('NO_BINDING', 'بدون صحافی'), ('COVERED_NO_PUNCH', 'کاور شده بدون پانچ'), ('COVERED_PUNCHED', 'کاور شده با پانچ')], max_length=21, verbose_name='نوع صحافی')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order', verbose_name='سفارش')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('برای سفارش', 'برای سفارش'), ('بازگشت وجه', 'بازگشت وجه')], max_length=21, verbose_name='علت تراکنش')),
                ('status', models.CharField(choices=[('پرداخت موفق', 'پرداخت موفق'), ('پرداخت ناموفق', 'پرداخت ناموفق')], max_length=21, verbose_name='وضعیت تراکنش')),
                ('description', models.TextField(verbose_name='توضیحات نراکنش')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='هزینه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش ها',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='order_order_created_3cbaa0_idx'),
        ),
    ]
