# Generated by Django 5.1.4 on 2025-01-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ثبت شده', 'ثبت شده'), ('پرداخت شده', 'پرداخت شده'), ('آماده سازی سفارش', 'آماده سازی سفارش'), ('در حال ارسال', 'در حال ارسال'), ('تکمیل شد', 'تکمیل شد'), ('لغو شد', 'لغو شد')], default='ثبت شده', max_length=21, verbose_name='وضعیت'),
        ),
    ]
