# Generated by Django 5.1.4 on 2025-01-11 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_documents_thumbnail'),
        ('order', '0003_alter_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='document',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='cart.documents', verbose_name='فایل'),
            preserve_default=False,
        ),
    ]
