# Generated by Django 5.1.4 on 2025-01-14 12:15

import order.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderitem_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=20, unique=True, verbose_name='کد تخفیف')),
                ('value', models.CharField(help_text='تخفیف به تومان یا درصد', max_length=6, validators=[order.models.discount_value_validator], verbose_name='مقدار تخفیف')),
                ('expire_at', models.DateTimeField(verbose_name='تاریخ انقضا')),
                ('used_by', models.ManyToManyField(related_name='used_discounts', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
