# Generated by Django 5.1.4 on 2025-01-14 12:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_discount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['-expire_at'], 'verbose_name': 'تخفیف', 'verbose_name_plural': 'تخفیف ها'},
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['-expire_at'], name='order_disco_expire__afd8d3_idx'),
        ),
    ]
