# Generated by Django 5.1.4 on 2025-01-14 12:48

import order.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_discount_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.CharField(help_text='تخفیف به تومان یا درصد', max_length=7, validators=[order.models.discount_value_validator], verbose_name='مقدار تخفیف'),
        ),
    ]
