# Generated by Django 5.1.4 on 2025-01-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_discount_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='print_type',
            field=models.CharField(choices=[('ONE_SIDE', 'یک رو'), ('BOTH_SIDES', 'دو رو'), ('TWO_PAGES_PER_SIDE', 'هر دو صفحه یک رو')], max_length=21, verbose_name='نوع چاپ'),
        ),
    ]
