# Generated by Django 5.1.4 on 2025-01-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_orderitem_print_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='postal_id',
            field=models.CharField(blank=True, null=True, verbose_name='کد رهگیری پست'),
        ),
    ]
