# Generated by Django 5.1.4 on 2025-01-16 11:25

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_order_postal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='expire_at',
            field=django_jalali.db.models.jDateTimeField(verbose_name='تاریخ انقضا'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
    ]
