# Generated by Django 5.1.4 on 2025-01-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_discount_expire_at_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='color',
            field=models.CharField(choices=[('WB', 'سیاه سفید'), ('C50', 'رنگی 50 درصد'), ('C100', 'رنگی 100 درصد')], max_length=21, verbose_name='رنگ'),
        ),
    ]
