# Generated by Django 5.1.4 on 2025-02-03 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_orderitem_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='order.order', verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('پرداخت نشده', 'پرداخت نشده'), ('پرداخت موفق', 'پرداخت موفق'), ('پرداخت ناموفق', 'پرداخت ناموفق')], max_length=21, verbose_name='وضعیت تراکنش'),
        ),
    ]
