# Generated by Django 5.1.4 on 2025-02-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_transaction_order_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(verbose_name='توضیحات تراکنش'),
        ),
    ]
