# Generated by Django 5.1.4 on 2025-02-03 14:28

import django_jalali.db.models
import jdatetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_transaction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='expire_at',
            field=django_jalali.db.models.jDateTimeField(default=jdatetime.datetime.today, verbose_name='تاریخ انقضا'),
        ),
    ]
