# Generated by Django 5.1.4 on 2025-02-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_discount_expire_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='extra',
            field=models.CharField(choices=[('NO_BINDING', 'بدون صحافی'), ('COVERED_NO_PUNCH', 'کاور شده بدون پانچ'), ('COVERED_PUNCHED', 'کاور شده با پانچ'), ('WIRE_BOUND', 'صحافی کامل با فنر')], max_length=21, verbose_name='نوع صحافی'),
        ),
    ]
