# Generated by Django 5.2.6 on 2025-09-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_alter_orderitem_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ثبت شده', 'ثبت شده'), ('پرداخت شده', 'پرداخت شده'), ('آماده سازی سفارش', 'آماده سازی سفارش'), ('آماده تحویل', 'آماده تحویل'), ('تکمیل شد', 'تکمیل شد'), ('لغو شد', 'لغو شد')], default='ثبت شده', max_length=21, verbose_name='وضعیت'),
        ),
    ]
